import packageJson from "../../package.json";

export const currentBuild = {
  version: `${packageJson.version}-mobile-ios-focus.20260614`,
  label: "Mobile iOS focus and safe-area pass",
  releasedAt: "2026-06-14",
};

export const releaseNotes = [
  {
    version: `${packageJson.version}-mobile-ios-focus.20260614`,
    label: "Mobile iOS focus and safe-area pass",
    releasedAt: "2026-06-14",
    entries: [
      "Client-side route changes now move focus to the new main content while hash targets such as feedback messages keep their targeted scroll behavior.",
      "Mobile header, status targets and detail back actions have explicit scroll offsets so focused content does not sit underneath the sticky header.",
      "The contact form keeps extra bottom safe-area breathing room for iOS Safari and uses a calmer compact mobile error summary.",
      "The mobile menu moves focus into the opened navigation and still returns focus to the toggle on Escape.",
      "A dedicated iPhone Pro Max mobile layout smoke covers 430 by 932 CSS pixels, touch input, Mobile Safari user agent, header overlap, bottom actions and detail ordering.",
    ],
  },
  {
    version: `${packageJson.version}-content-canonical-refresh.20260614`,
    label: "Content and canonical refresh",
    releasedAt: "2026-06-14",
    entries: [
      "Route-specific canonical metadata now points search, detail, contact, legal and help pages to their own www.null-noise.de URLs instead of the home page.",
      "The explanation page now describes the current live address, Vercel hosting, Prisma Postgres data path, server-side TMDb reads and SMTP contact boundary.",
      "The accessibility page now references www.null-noise.de, the current WCAG 2.2 AA technical test path and the remaining manual/device-review boundary.",
      "Privacy, contact and imprint copy now reflect the private preview gate, visible contact address, server-side SMTP contact handling and canonical www domain.",
      "No product logic, database schema, environment variables or write behavior changed in this content pass.",
    ],
  },
  {
    version: `${packageJson.version}-production-launch.20260614`,
    label: "Production launch",
    releasedAt: "2026-06-14",
    entries: [
      "The current Production deployment is live on www.null-noise.de with the apex domain redirecting permanently to the www domain.",
      "The Vercel build now runs prisma generate before next build so the deployed Prisma Client matches the PostgreSQL schema instead of a cached SQLite client.",
      "Catalog bootstrap now skips the seed transaction when the expected seed titles and aggregates already exist, reducing cold-start write pressure.",
      "Live smoke covered core routes, catalog APIs, TMDb search APIs and the private preview gate.",
      "Live rating smoke succeeded with a slow submit and returned the expected too-fast guard on an immediate follow-up instead of rating=error.",
      "No environment variables were changed and no production migration was rerun during the final handoff.",
      "The full accessibility suite should be rerun after these final hotfix commits.",
    ],
  },
  {
    version: `${packageJson.version}-postgres-prep.20260614`,
    label: "Postgres preparation",
    releasedAt: "2026-06-14",
    entries: [
      "Prisma is prepared locally for PostgreSQL instead of SQLite, with the generated initial migration applied only to the Vercel Development database.",
      "Local DB setup scripts now use Prisma migrate commands for the normal Postgres path instead of the SQLite bootstrap helper.",
      "Unit tests now require a separate disposable Prisma Postgres test database via NULL_NOISE_TEST_DATABASE_URL so shared Development or Production data is not reset by tests.",
      "The initial migration has been verified against the separate test database, and unit tests pass on that isolated Postgres path.",
      "The global navigation loader is hidden with visibility while inactive so automated contrast scans do not evaluate a fully transparent loading label.",
      "Production writes stay inactive; NULL_NOISE_ENABLE_WRITES was not changed.",
      "No database URLs, credentials or secret values are exposed in release metadata or documentation.",
    ],
  },
  {
    version: `${packageJson.version}-image-cache-costs.20260613`,
    label: "Image cache cost controls",
    releasedAt: "2026-06-13",
    entries: [
      "TMDb poster optimization now uses a 31 day image cache TTL to reduce repeated Vercel Image Cache Writes for rarely changing poster assets.",
      "Result-card poster sizes are constrained to thumbnail-realistic widths so mobile and desktop views request fewer oversized image variants.",
      "Detail posters use the bounded TMDb w780 source instead of original poster assets, preserving the layout while reducing transformation weight.",
      "The local poster proxy now advertises the same long cache window for poster responses.",
      "Release and testing docs now call out Image Optimization usage, cache writes and poster variant discipline before deploy.",
    ],
  },
  {
    version: `${packageJson.version}-preview-gate-mobile-polish.20260613`,
    label: "Preview gate and mobile polish",
    releasedAt: "2026-06-13",
    entries: [
      "The public app is now fronted by a lightweight client-side preview gate with a centered teaser page, logo and the preview phrase.",
      "Mobile detail pages place the detail poster directly below the title heading before the first assessment.",
      "Mobile result-card actions stay in the text column and no longer overlap poster thumbnails.",
      "The local remembered/seen shelf renders only groups with content, so a single Schon gesehen group uses the full shelf width.",
      "A global navigation progress indicator appears during pending route-data loads and respects reduced-motion preferences.",
    ],
  },
  {
    version: `${packageJson.version}-mobile-search-repair.20260613`,
    label: "Mobile search repair",
    releasedAt: "2026-06-13",
    entries: [
      "Empty search URLs such as /suche?q=&tone=all&kind=all stay in the calm browse state instead of rendering a broken mixed search view.",
      "The opened mobile menu is compact, stays inside the content width and keeps a proportional keyboard focus style on the menu button.",
      "Mobile search result cards use the available width more fully, keep posters secondary and preserve text labels on card actions.",
      "Footer release information remains visible but is visually quieter on narrow screens.",
      "Loading states now use a clearer status box with visible text, a stronger indicator and reduced-motion-safe behavior.",
    ],
  },
  {
    version: `${packageJson.version}-quiet-loading.20260613`,
    label: "Quiet loading states",
    releasedAt: "2026-06-13",
    entries: [
      "Search, contact submit and app-route loading now share a quiet text-first loading state for real pending work only.",
      "Search result updates keep existing content in place, expose one concise live status and avoid a second broad live region around the results.",
      "The contact form keeps duplicate-submit protection and shows a calm sending state without adding artificial delay.",
      "Loading motion stays decorative and is disabled under prefers-reduced-motion while status text remains visible.",
      "The imprint copy now references the canonical null-noise.de domain and keeps the missing legal address as an explicit review boundary.",
    ],
  },
  {
    version: `${packageJson.version}-production-domain.20260613`,
    label: "Production domain switch",
    releasedAt: "2026-06-13",
    entries: [
      "The canonical public address is now www.null-noise.de via NEXT_PUBLIC_SITE_URL.",
      "The apex domain null-noise.de redirects permanently to the www domain in Vercel.",
      "Visible legal and accessibility contact copy now uses hallo@null-noise.de.",
      "The contact form remains server-side SMTP through environment variables; no secrets or SMTP credentials are exposed in client code.",
      "The Vercel project address null-noise.vercel.app remains only a technical non-canonical project address.",
    ],
  },
  {
    version: `${packageJson.version}-contact-smtp-mailbox.20260607`,
    label: "SMTP mailbox switch",
    releasedAt: "2026-06-07",
    entries: [
      "The contact form now sends server-side via SMTP with mail@sebastianjansen.com as the technical sender address.",
      "Contact requests are no longer stored through an admin area, temporary file, local database or Blob storage path.",
      "The optional form email is used only as Reply-To; the recipient stays server-side in CONTACT_TO_EMAIL.",
      "Validation, a character counter, generic failure copy, a honeypot field, body-size limiting and lightweight rate limiting stay in place.",
      "Privacy copy, environment examples, local tests and release documentation were synchronized for the SMTP contact boundary.",
    ],
  },
  {
    version: `${packageJson.version}-mobile-layout.20260606`,
    label: "Mobile layout stabilization",
    releasedAt: "2026-06-06",
    entries: [
      "Narrow mobile layouts were tightened across contact, accessibility, search results, title detail, footer and the mobile navigation without changing product logic.",
      "The mobile menu button keeps a visible icon at 320px and the opened menu uses denser link spacing while preserving active-route and focus states.",
      "Result cards on very narrow screens now stack poster, title, reading copy and actions instead of squeezing actions into a cramped row.",
      "Contact form controls, WCAG matrix blocks, status badges and footer release strings are bounded to their container and can wrap safely.",
      "Automated mobile checks now verify 320px, 390px and 430px for route-level document width plus central card, form, matrix and footer element bounds.",
    ],
  },
  {
    version: `${packageJson.version}-contact-send.20260606`,
    label: "Privacy-first contact sending",
    releasedAt: "2026-06-06",
    entries: [
      "A native contact page is reachable from the footer on every route, with the message as the only required field and the reply email kept optional.",
      "The form now sends through a server-side contact endpoint instead of a mailto handoff; mail provider keys stay server-only.",
      "Local validation, server validation, visible field errors, a focusable error summary and a polite success status remain in place without tracking, accounts, CAPTCHA or durable message storage.",
      "The submit control now uses the plain label Nachricht senden and guards against duplicate submits while keeping focus stable.",
      "The required message field now exposes a live character counter that says how many characters are still missing and switches to Mindestlänge erreicht at 10 characters without relying on color alone.",
      "If SMTP environment variables are missing, the API returns a generic send failure instead of a false success.",
      "Mobile contact, footer release and WCAG matrix layouts were hardened against long text overflow at 320px, 390px and 430px.",
      "The technical WCAG 2.2 A/AA/AAA matrix now includes /kontakt as a core route and covers form labels, help text, error suggestions, status messages, keyboard flow, reflow, text spacing and target size.",
      "WCAG 2.2 AA remains the technical target standard; AAA checks stay exploratory and manual conformance review remains a separate boundary.",
    ],
  },
  {
    version: `${packageJson.version}-wcag-lighthouse.20260605`,
    label: "WCAG and Lighthouse polish",
    releasedAt: "2026-06-05",
    entries: [
      "The focused skip link now appears immediately instead of waiting for a transition, keeping bypass navigation visibly available as soon as it receives keyboard focus.",
      "Obsolete pre-SVG brand lockup CSS was removed from the global stylesheet without touching the current logo, wordmark frame, focus, active-route or mobile-menu states.",
      "Local Lighthouse mobile checks remained stable while the large CSS resource and unused-CSS estimate dropped slightly.",
      "WCAG 2.2 Level AA is sharpened as the technical target standard, with manual review still named as a boundary for real conformance assessment.",
      "A dedicated WCAG 2.2 A/AA technical matrix now records every success criterion with repeatable automated checks or feature-based N/A evidence.",
      "Automated regression coverage expanded across axe-core, Playwright keyboard, reflow, reduced-motion, text-spacing, target-size and mobile-menu smokes on the core route set.",
      "Result-card action names now keep visible labels such as Details, Merken and Gesehen? inside the accessible name, while card text contrast no longer depends on opacity fades.",
    ],
  },
  {
    version: `${packageJson.version}-header.20260605`,
    label: "Header navigation boundary",
    releasedAt: "2026-06-05",
    entries: [
      "The site header now stays server-rendered while the interactive navigation state lives in a smaller client component.",
      "The mobile menu keeps native button, nav, list and link semantics, with Escape returning focus to the menu button.",
      "Scroll-state styling and unused scrolled-header CSS were removed without dropping visible focus, active-route styling or the opaque mobile menu layer.",
      "Local validation for this pass covered lint, production build, unit tests, axe-core, a11y and the full Playwright suite before the Git push and Vercel preview deploy.",
    ],
  },
  {
    version: `${packageJson.version}-pwa.20260530`,
    label: "PWA and offline baseline",
    releasedAt: "2026-05-30",
    entries: [
      "Manifest, theme colors and app icons now cover the installable baseline, including a maskable icon.",
      "The service worker keeps navigation requests on a local offline page when the network is unavailable.",
      "The offline page clearly marks new hits and external title data as connection-dependent instead of implying offline availability.",
      "Merkliste and Gesehen hints remain browser-local and can still be shown on the offline page when local app code is available.",
      "Short functional transitions now support focus, hover, disclosure, activation and loading states while respecting reduced motion.",
      "The Typekit runtime stylesheet was removed, and the homepage heading order and browse-link accessible names were corrected.",
      "Local automated checks for lint, build, unit, axe-core, a11y and Playwright passed before this handoff.",
    ],
  },
  {
    version: `${packageJson.version}-detail-mobile.20260525`,
    label: "Mobile title detail layout",
    releasedAt: "2026-05-25",
    entries: [
      "Mobile title detail pages now place the poster directly after the title before the first assessment.",
      "The first assessment follows the poster, with the synopsis shown after the assessment in the same semantic order.",
      "Poster fallbacks stay proportional on narrow screens so missing artwork does not create oversized empty space.",
      "Mobile detail ordering, focus flow and touch-friendly controls were checked at 375x667 and 430x932.",
    ],
  },
  {
    version: `${packageJson.version}-cards.20260524`,
    label: "Result card clarity",
    releasedAt: "2026-05-24",
    entries: [
      "TMDb result card toplines now include the first available genre between format and year.",
      "Card footer actions now use clearer visual roles and icons for Details, Merken and Gesehen.",
      "Read-only external cards explain that only title metadata is available instead of using a vague generic note.",
    ],
  },
  {
    version: `${packageJson.version}-discovery.20260524`,
    label: "Situational discovery UX",
    releasedAt: "2026-05-24",
    entries: [
      "Browse groups now use calmer situational entry points such as Chillig, Mal so, mal so and Stressig.",
      "External result cards can surface not-now language like Kann gerade zu dicht sein without turning it into a negative rating.",
      "Detail disclosures group evidence as spricht eher dafuer, kann dagegen sprechen and Datenlage, while keeping scores, percentages and rankings hidden.",
      "Follow-up sections now frame alternatives as situational counterweights instead of classic similar-title recommendations.",
      "The new copy is derived from existing Evidence/TMDb summaries only; no profile, tracking, social or new external-source logic was added.",
    ],
  },
  {
    version: `${packageJson.version}-evidence.20260524`,
    label: "Evidence calibration and browse diversity",
    releasedAt: "2026-05-24",
    entries: [
      "Evidence aggregation now evaluates axes and conflicts instead of flattening everything into one overall score.",
      "Genre-only metadata stays weak; repeated matching keywords can raise confidence, while synopsis remains defensive.",
      "Relief and predictability can soften a title, emotional load stays separate from audio or visual intensity, and contradictory signals remain wechselhaft.",
      "TMDb browse now rotates controlled discover strategies across genre, popularity, vote-count and year windows before evidence grouping.",
      "Browse picks use seeded deterministic shuffling and diversity buckets, so suggestions vary without becoming arbitrary or personalized.",
      "Optional Does the Dog Die and Common Sense Media adapters remain inactive Noop/Fallback boundaries without keys.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260524`,
    label: "Mobile viewport and card repair",
    releasedAt: "2026-05-24",
    entries: [
      "Mobile header, app shell, menu overlay and page content now share one content gutter on small viewports.",
      "The opened mobile menu stays inside the viewport, uses a fully opaque layer and avoids the former bright right-side strip.",
      "The menu button changes the hamburger into a close icon while preserving the text label and existing ARIA state.",
      "Mobile menu active-route styling is visually distinct from keyboard focus, with focus outlines remaining visible.",
      "Result cards on mobile now give Details its own full-width row and leave more room between Merken and Gesehen without changing product logic.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260523`,
    label: "Mobile navigation, search and accessibility wording",
    releasedAt: "2026-05-23",
    entries: [
      "Mobile navigation now contains only Start, Suche and Erklärung / Hilfe; legal and accessibility links stay reachable from the footer.",
      "The mobile menu uses an opaque high-contrast layer, clearer active-route treatment, larger tap areas and the existing Escape/button/link close behavior.",
      "Mobile spacing, card rhythm, local shelf controls, footer links and legal/help pages were tightened for calmer small-screen reading.",
      "Free search keeps seen-title hiding out of typed search results so known queries do not silently collapse to a single visible card.",
      "Successful TMDb searches are briefly reused server-side when the same query is checked again and the upstream search stumbles.",
      "The accessibility page now focuses on WCAG 2.2 AA as the technical target, current status, implemented measures, test approach, known limits and contact.",
      "Favicon and share metadata were refreshed with a simplified TV mark and a cache-busted Open Graph image.",
      "Result cards now keep Details, Merken and Gesehen as one mobile action row, including the 320px reflow check.",
      "The header brand lockup stays aligned to the viewport edge across breakpoints instead of drifting with the centered shell.",
    ],
  },
  {
    version: `${packageJson.version}-joy.20260522`,
    label: "Product states and calmer software feel",
    releasedAt: "2026-05-22",
    entries: [
      "Search now shows the current frame as compact state chips for title, direction, format, peaks and density without adding scores or rankings.",
      "Local Merken and Schon gesehen actions now expose a clearer browser-local state on result cards and detail pages.",
      "Detail pages surface direction, current status and confidence as a short decision strip near the first assessment.",
      "Direct browse arrows and the secondary browse action were visually tightened into calmer, button-like controls while keeping native link semantics.",
      "The mobile hamburger menu is now focused on primary product pages while legal pages remain reachable from the footer only.",
      "Verification for this pass: lint, build, unit, axe-core, a11y, full Playwright and 320px/390px/430px/desktop route smokes passed.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260517`,
    label: "Mobile header, motion and detail layout hardening",
    releasedAt: "2026-05-17",
    entries: [
      "Mobile header is now a client-side fixed app shell with a burger menu, Escape handling, active route state and symmetric safe-area spacing.",
      "Mobile menu layering was hardened so the navigation overlay stays above page content in mobile browser stacking contexts.",
      "Hidden skip links no longer intercept taps on the logo/wordmark while remaining keyboard-focusable.",
      "Scroll compaction, glass backdrop, menu opening, cards and page transitions now use short CSS transitions while preserving `prefers-reduced-motion`.",
      "Mobile detail pages keep poster, title, type/year, synopsis, first assessment, status, availability and recommendations visible in the intended reading order.",
      "Mobile typography, touch targets, footer rhythm, result cards, legal text contrast and metadata-detail back navigation were tightened without changing product logic.",
      "Search browse links are now presented as button-style CTAs with a small magnifier icon while keeping native link semantics.",
      "Direct browse starts now have roomier inner spacing and green, gold and red category surfaces for calm, mixed and intense directions.",
      "Favicon, Open Graph/Twitter metadata and the generated social image were refreshed with current null-noise copy and logo-derived colors.",
      "Local verification for this pass: `npm run lint`, `npm run build`, `npm run test:a11y` and manual 390px/430px viewport checks passed.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260515`,
    label: "Mobile orientation, navigation and terminology pass",
    releasedAt: "2026-05-15",
    entries: [
      "Mobile onboarding copy now explains search, coarse stimulus orientation and the three visible categories before the primary search flow.",
      "Detail page callout visibility was restored on small viewports so confidence, basis and feedback count remain available near the first decision.",
      "Header navigation now stays scoped to primary product links while footer metadata navigation keeps Accessibility, Privacy and Imprint reachable.",
      "User-facing copy now uses `Erste Einschätzung` instead of the previous internal wording across UI, help copy and related tests.",
      "Footer release metadata was updated before the Git push and Vercel deploy step for this mobile-orientation pass.",
    ],
  },
  {
    version: "0.8.4",
    label: "Legal pages and mobile UI maintenance",
    releasedAt: "2026-05-14",
    entries: [
      "Legal pages now use the verified contact address for Sebastian Jansen and keep the missing postal address as an explicit review item instead of inventing data.",
      "Accessibility, privacy and imprint copy were aligned with the current private hobby/reference-project scope.",
      "Footer release metadata now uses a more technical build/changelog vocabulary and reflects the latest legal-page update.",
      "Header, hero, search form, direction tiles, mobile result lists and footer layout remain stabilized against clipped text and horizontal overflow.",
    ],
  },
  {
    version: "0.8.3",
    label: "Metadata spike layout stabilization",
    releasedAt: "2026-04-18",
    entries: [
      "Refined the metadata detail layout with a clearer main column and a flatter secondary information column.",
      "Compacted `Dazu passt auch ...` cards to reduce scroll load while keeping the first assessment visible.",
      "Moved `Verfügbar bei` into a quieter secondary section with more predictable reading rhythm.",
      "Hardened `/suche` direct-start cards as responsive targets with stable focus and click areas.",
      "Removed the doubled left edge in browse groups caused by overlapping wrapper and group borders.",
    ],
  },
  {
    version: "0.8.2",
    label: "Local title import",
    releasedAt: "2026-03-28",
    entries: [
      "Added an explicit path for importing external TMDb titles into local null-noise records with provisional seed data.",
      "Search now routes imported titles to the local detail page with the rating form instead of only showing metadata.",
      "Kept TMDb scoped to metadata; stimulus profile, effect, confidence and aggregation stay internal to null-noise.",
    ],
  },
  {
    version: "0.8.1",
    label: "Rating write path hardening",
    releasedAt: "2026-03-28",
    entries: [
      "Added server-side guards for anonymous ratings: origin check, rate limit, title cooldown and a small timing plausibility check.",
      "Kept success and rejection feedback calm in the UI without introducing accounts or profile building.",
      "Maintained separate aggregation for stimulus profile and soothing effect, independent from metadata context.",
    ],
  },
  {
    version: "0.7.0",
    label: "Separate effect dimension",
    releasedAt: "2026-03-27",
    entries: [
      "Extended the stimulus model with the separate `soothingEffect` dimension.",
      "Aggregated mock data from discrete sample ratings via median values for profile and soothing effect.",
      "Added the subjective soothing-effect readout and prepared the fourth rating question on detail pages.",
    ],
  },
  {
    version: "0.6.2",
    label: "Claim integration",
    releasedAt: "2026-03-27",
    entries: [
      "Integrated the product claim into the homepage and anchored it below the product name.",
      "Aligned homepage, search and explanation copy around calm orientation and provisional assessment.",
      "Updated metadata and sharing text without moving the product surface toward marketing copy.",
    ],
  },
  {
    version: "0.6.1",
    label: "Muted poster assets",
    releasedAt: "2026-03-27",
    entries: [
      "Enabled small poster thumbnails for external primary results as optional visual orientation.",
      "Routed posters through a local server path and rendered them desaturated, greyed and slightly dimmed.",
      "Kept cards stable when no poster asset is available.",
    ],
  },
  {
    version: "0.6.0",
    label: "Stimulus profile simplification",
    releasedAt: "2026-03-27",
    entries: [
      "Simplified the stimulus profile into three named audio axes with a shared 0-to-4 scale.",
      "Derived confidence from the number of assessments and exposed it as low, medium or high.",
      "Deferred direct poster loading to keep metadata context and privacy behavior easier to reason about.",
    ],
  },
  {
    version: "0.5.2",
    label: "Logo placeholder refresh",
    releasedAt: "2026-03-27",
    entries: [
      "Reworked the placeholder mark into a brighter, softer face shape.",
      "Removed the dark backing block so the mark reads lighter at small sizes.",
      "Updated visible footer build metadata to 0.5.2.",
    ],
  },
  {
    version: "0.5.0",
    label: "Editorial UI pass",
    releasedAt: "2026-03-27",
    entries: [
      "Moved the UI toward a lighter editorial language with calmer typography and less card weight.",
      "Aligned header, footer, homepage and search page around a reduced layout system.",
      "Updated placeholder logo, favicon and sharing preview for the new visual direction.",
    ],
  },
  {
    version: "0.4.4",
    label: "TMDb suggestions",
    releasedAt: "2026-03-27",
    entries: [
      "Added server-side TMDb suggestions while typing in the search field.",
      "Rendered suggestions as a separate list below the field without replacing stimulus profiles.",
      "Weighted short, likely title completions higher in TMDb relevance sorting.",
    ],
  },
  {
    version: "0.1.0",
    label: "MVP baseline",
    releasedAt: "2026-03-22",
    entries: [
      "Shipped the first search and detail surface with accessibility goals and mock data.",
      "Added the initial explanation system, usage guidance and semantic UI building blocks.",
    ],
  },
] as const;
