import packageJson from "../../package.json";

export const currentBuild = {
  version: `${packageJson.version}-contact-send.20260606`,
  label: "Privacy-first contact sending",
  releasedAt: "2026-06-06",
};

export const releaseNotes = [
  {
    version: `${packageJson.version}-contact-send.20260606`,
    label: "Privacy-first contact sending",
    releasedAt: "2026-06-06",
    entries: [
      "A native contact page is reachable from the footer on every route, with the message as the only required field and the reply email kept optional.",
      "The form now sends through a server-side contact endpoint instead of a mailto handoff; mail provider keys stay server-only.",
      "Local validation, server validation, visible field errors, a focusable error summary and a polite success status remain in place without tracking, accounts, CAPTCHA or durable message storage.",
      "The submit control now uses the plain label Nachricht senden and guards against duplicate submits while keeping focus stable.",
      "The required message field now exposes a live character counter that says how many characters are still missing and switches to Mindestlänge erreicht at 10 characters without relying on color alone.",
      "If contact mail environment variables are missing, local and test runs use a dry success path while Production returns an explicit setup error instead of a false success.",
      "Mobile contact, footer release and WCAG matrix layouts were hardened against long text overflow at 320px, 390px and 430px.",
      "The technical WCAG 2.2 A/AA/AAA matrix now includes /kontakt as a core route and covers form labels, help text, error suggestions, status messages, keyboard flow, reflow, text spacing and target size.",
      "WCAG 2.2 AA remains the technical target standard; AAA checks stay exploratory and manual conformance review remains a separate boundary.",
    ],
  },
  {
    version: `${packageJson.version}-wcag-lighthouse.20260605`,
    label: "WCAG and Lighthouse polish",
    releasedAt: "2026-06-05",
    entries: [
      "The focused skip link now appears immediately instead of waiting for a transition, keeping bypass navigation visibly available as soon as it receives keyboard focus.",
      "Obsolete pre-SVG brand lockup CSS was removed from the global stylesheet without touching the current logo, wordmark frame, focus, active-route or mobile-menu states.",
      "Local Lighthouse mobile checks remained stable while the large CSS resource and unused-CSS estimate dropped slightly.",
      "WCAG 2.2 Level AA is sharpened as the technical target standard, with manual review still named as a boundary for real conformance assessment.",
      "A dedicated WCAG 2.2 A/AA technical matrix now records every success criterion with repeatable automated checks or feature-based N/A evidence.",
      "Automated regression coverage expanded across axe-core, Playwright keyboard, reflow, reduced-motion, text-spacing, target-size and mobile-menu smokes on the core route set.",
      "Result-card action names now keep visible labels such as Details, Merken and Gesehen? inside the accessible name, while card text contrast no longer depends on opacity fades.",
    ],
  },
  {
    version: `${packageJson.version}-header.20260605`,
    label: "Header navigation boundary",
    releasedAt: "2026-06-05",
    entries: [
      "The site header now stays server-rendered while the interactive navigation state lives in a smaller client component.",
      "The mobile menu keeps native button, nav, list and link semantics, with Escape returning focus to the menu button.",
      "Scroll-state styling and unused scrolled-header CSS were removed without dropping visible focus, active-route styling or the opaque mobile menu layer.",
      "Local validation for this pass covered lint, production build, unit tests, axe-core, a11y and the full Playwright suite before the Git push and Vercel preview deploy.",
    ],
  },
  {
    version: `${packageJson.version}-pwa.20260530`,
    label: "PWA and offline baseline",
    releasedAt: "2026-05-30",
    entries: [
      "Manifest, theme colors and app icons now cover the installable baseline, including a maskable icon.",
      "The service worker keeps navigation requests on a local offline page when the network is unavailable.",
      "The offline page clearly marks new hits and external title data as connection-dependent instead of implying offline availability.",
      "Merkliste and Gesehen hints remain browser-local and can still be shown on the offline page when local app code is available.",
      "Short functional transitions now support focus, hover, disclosure, activation and loading states while respecting reduced motion.",
      "The Typekit runtime stylesheet was removed, and the homepage heading order and browse-link accessible names were corrected.",
      "Local automated checks for lint, build, unit, axe-core, a11y and Playwright passed before this handoff.",
    ],
  },
  {
    version: `${packageJson.version}-detail-mobile.20260525`,
    label: "Mobile title detail layout",
    releasedAt: "2026-05-25",
    entries: [
      "Mobile title detail pages now place the poster directly after the title before the first assessment.",
      "The first assessment follows the poster, with the synopsis shown after the assessment in the same semantic order.",
      "Poster fallbacks stay proportional on narrow screens so missing artwork does not create oversized empty space.",
      "Mobile detail ordering, focus flow and touch-friendly controls were checked at 375x667 and 430x932.",
    ],
  },
  {
    version: `${packageJson.version}-cards.20260524`,
    label: "Result card clarity",
    releasedAt: "2026-05-24",
    entries: [
      "TMDb result card toplines now include the first available genre between format and year.",
      "Card footer actions now use clearer visual roles and icons for Details, Merken and Gesehen.",
      "Read-only external cards explain that only title metadata is available instead of using a vague generic note.",
    ],
  },
  {
    version: `${packageJson.version}-discovery.20260524`,
    label: "Situational discovery UX",
    releasedAt: "2026-05-24",
    entries: [
      "Browse groups now use calmer situational entry points such as Chillig, Mal so, mal so and Stressig.",
      "External result cards can surface not-now language like Kann gerade zu dicht sein without turning it into a negative rating.",
      "Detail disclosures group evidence as spricht eher dafuer, kann dagegen sprechen and Datenlage, while keeping scores, percentages and rankings hidden.",
      "Follow-up sections now frame alternatives as situational counterweights instead of classic similar-title recommendations.",
      "The new copy is derived from existing Evidence/TMDb summaries only; no profile, tracking, social or new external-source logic was added.",
    ],
  },
  {
    version: `${packageJson.version}-evidence.20260524`,
    label: "Evidence calibration and browse diversity",
    releasedAt: "2026-05-24",
    entries: [
      "Evidence aggregation now evaluates axes and conflicts instead of flattening everything into one overall score.",
      "Genre-only metadata stays weak; repeated matching keywords can raise confidence, while synopsis remains defensive.",
      "Relief and predictability can soften a title, emotional load stays separate from audio or visual intensity, and contradictory signals remain wechselhaft.",
      "TMDb browse now rotates controlled discover strategies across genre, popularity, vote-count and year windows before evidence grouping.",
      "Browse picks use seeded deterministic shuffling and diversity buckets, so suggestions vary without becoming arbitrary or personalized.",
      "Optional Does the Dog Die and Common Sense Media adapters remain inactive Noop/Fallback boundaries without keys.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260524`,
    label: "Mobile viewport and card repair",
    releasedAt: "2026-05-24",
    entries: [
      "Mobile header, app shell, menu overlay and page content now share one content gutter on small viewports.",
      "The opened mobile menu stays inside the viewport, uses a fully opaque layer and avoids the former bright right-side strip.",
      "The menu button changes the hamburger into a close icon while preserving the text label and existing ARIA state.",
      "Mobile menu active-route styling is visually distinct from keyboard focus, with focus outlines remaining visible.",
      "Result cards on mobile now give Details its own full-width row and leave more room between Merken and Gesehen without changing product logic.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260523`,
    label: "Mobile navigation, search and accessibility wording",
    releasedAt: "2026-05-23",
    entries: [
      "Mobile navigation now contains only Start, Suche and Erklärung / Hilfe; legal and accessibility links stay reachable from the footer.",
      "The mobile menu uses an opaque high-contrast layer, clearer active-route treatment, larger tap areas and the existing Escape/button/link close behavior.",
      "Mobile spacing, card rhythm, local shelf controls, footer links and legal/help pages were tightened for calmer small-screen reading.",
      "Free search keeps seen-title hiding out of typed search results so known queries do not silently collapse to a single visible card.",
      "Successful TMDb searches are briefly reused server-side when the same query is checked again and the upstream search stumbles.",
      "The accessibility page now focuses on WCAG 2.2 AA as the technical target, current status, implemented measures, test approach, known limits and contact.",
      "Favicon and share metadata were refreshed with a simplified TV mark and a cache-busted Open Graph image.",
      "Result cards now keep Details, Merken and Gesehen as one mobile action row, including the 320px reflow check.",
      "The header brand lockup stays aligned to the viewport edge across breakpoints instead of drifting with the centered shell.",
    ],
  },
  {
    version: `${packageJson.version}-joy.20260522`,
    label: "Product states and calmer software feel",
    releasedAt: "2026-05-22",
    entries: [
      "Search now shows the current frame as compact state chips for title, direction, format, peaks and density without adding scores or rankings.",
      "Local Merken and Schon gesehen actions now expose a clearer browser-local state on result cards and detail pages.",
      "Detail pages surface direction, current status and confidence as a short decision strip near the first assessment.",
      "Direct browse arrows and the secondary browse action were visually tightened into calmer, button-like controls while keeping native link semantics.",
      "The mobile hamburger menu is now focused on primary product pages while legal pages remain reachable from the footer only.",
      "Verification for this pass: lint, build, unit, axe-core, a11y, full Playwright and 320px/390px/430px/desktop route smokes passed.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260517`,
    label: "Mobile header, motion and detail layout hardening",
    releasedAt: "2026-05-17",
    entries: [
      "Mobile header is now a client-side fixed app shell with a burger menu, Escape handling, active route state and symmetric safe-area spacing.",
      "Mobile menu layering was hardened so the navigation overlay stays above page content in mobile browser stacking contexts.",
      "Hidden skip links no longer intercept taps on the logo/wordmark while remaining keyboard-focusable.",
      "Scroll compaction, glass backdrop, menu opening, cards and page transitions now use short CSS transitions while preserving `prefers-reduced-motion`.",
      "Mobile detail pages keep poster, title, type/year, synopsis, first assessment, status, availability and recommendations visible in the intended reading order.",
      "Mobile typography, touch targets, footer rhythm, result cards, legal text contrast and metadata-detail back navigation were tightened without changing product logic.",
      "Search browse links are now presented as button-style CTAs with a small magnifier icon while keeping native link semantics.",
      "Direct browse starts now have roomier inner spacing and green, gold and red category surfaces for calm, mixed and intense directions.",
      "Favicon, Open Graph/Twitter metadata and the generated social image were refreshed with current null-noise copy and logo-derived colors.",
      "Local verification for this pass: `npm run lint`, `npm run build`, `npm run test:a11y` and manual 390px/430px viewport checks passed.",
    ],
  },
  {
    version: `${packageJson.version}-mobile.20260515`,
    label: "Mobile orientation, navigation and terminology pass",
    releasedAt: "2026-05-15",
    entries: [
      "Mobile onboarding copy now explains search, coarse stimulus orientation and the three visible categories before the primary search flow.",
      "Detail page callout visibility was restored on small viewports so confidence, basis and feedback count remain available near the first decision.",
      "Header navigation now stays scoped to primary product links while footer metadata navigation keeps Accessibility, Privacy and Imprint reachable.",
      "User-facing copy now uses `Erste Einschätzung` instead of the previous internal wording across UI, help copy and related tests.",
      "Footer release metadata was updated before the Git push and Vercel deploy step for this mobile-orientation pass.",
    ],
  },
  {
    version: "0.8.4",
    label: "Legal pages and mobile UI maintenance",
    releasedAt: "2026-05-14",
    entries: [
      "Legal pages now use the verified contact address for Sebastian Jansen and keep the missing postal address as an explicit review item instead of inventing data.",
      "Accessibility, privacy and imprint copy were aligned with the current private hobby/reference-project scope.",
      "Footer release metadata now uses a more technical build/changelog vocabulary and reflects the latest legal-page update.",
      "Header, hero, search form, direction tiles, mobile result lists and footer layout remain stabilized against clipped text and horizontal overflow.",
    ],
  },
  {
    version: "0.8.3",
    label: "Metadata spike layout stabilization",
    releasedAt: "2026-04-18",
    entries: [
      "Refined the metadata detail layout with a clearer main column and a flatter secondary information column.",
      "Compacted `Dazu passt auch ...` cards to reduce scroll load while keeping the first assessment visible.",
      "Moved `Verfügbar bei` into a quieter secondary section with more predictable reading rhythm.",
      "Hardened `/suche` direct-start cards as responsive targets with stable focus and click areas.",
      "Removed the doubled left edge in browse groups caused by overlapping wrapper and group borders.",
    ],
  },
  {
    version: "0.8.2",
    label: "Local title import",
    releasedAt: "2026-03-28",
    entries: [
      "Added an explicit path for importing external TMDb titles into local null-noise records with provisional seed data.",
      "Search now routes imported titles to the local detail page with the rating form instead of only showing metadata.",
      "Kept TMDb scoped to metadata; stimulus profile, effect, confidence and aggregation stay internal to null-noise.",
    ],
  },
  {
    version: "0.8.1",
    label: "Rating write path hardening",
    releasedAt: "2026-03-28",
    entries: [
      "Added server-side guards for anonymous ratings: origin check, rate limit, title cooldown and a small timing plausibility check.",
      "Kept success and rejection feedback calm in the UI without introducing accounts or profile building.",
      "Maintained separate aggregation for stimulus profile and soothing effect, independent from metadata context.",
    ],
  },
  {
    version: "0.7.0",
    label: "Separate effect dimension",
    releasedAt: "2026-03-27",
    entries: [
      "Extended the stimulus model with the separate `soothingEffect` dimension.",
      "Aggregated mock data from discrete sample ratings via median values for profile and soothing effect.",
      "Added the subjective soothing-effect readout and prepared the fourth rating question on detail pages.",
    ],
  },
  {
    version: "0.6.2",
    label: "Claim integration",
    releasedAt: "2026-03-27",
    entries: [
      "Integrated the product claim into the homepage and anchored it below the product name.",
      "Aligned homepage, search and explanation copy around calm orientation and provisional assessment.",
      "Updated metadata and sharing text without moving the product surface toward marketing copy.",
    ],
  },
  {
    version: "0.6.1",
    label: "Muted poster assets",
    releasedAt: "2026-03-27",
    entries: [
      "Enabled small poster thumbnails for external primary results as optional visual orientation.",
      "Routed posters through a local server path and rendered them desaturated, greyed and slightly dimmed.",
      "Kept cards stable when no poster asset is available.",
    ],
  },
  {
    version: "0.6.0",
    label: "Stimulus profile simplification",
    releasedAt: "2026-03-27",
    entries: [
      "Simplified the stimulus profile into three named audio axes with a shared 0-to-4 scale.",
      "Derived confidence from the number of assessments and exposed it as low, medium or high.",
      "Deferred direct poster loading to keep metadata context and privacy behavior easier to reason about.",
    ],
  },
  {
    version: "0.5.2",
    label: "Logo placeholder refresh",
    releasedAt: "2026-03-27",
    entries: [
      "Reworked the placeholder mark into a brighter, softer face shape.",
      "Removed the dark backing block so the mark reads lighter at small sizes.",
      "Updated visible footer build metadata to 0.5.2.",
    ],
  },
  {
    version: "0.5.0",
    label: "Editorial UI pass",
    releasedAt: "2026-03-27",
    entries: [
      "Moved the UI toward a lighter editorial language with calmer typography and less card weight.",
      "Aligned header, footer, homepage and search page around a reduced layout system.",
      "Updated placeholder logo, favicon and sharing preview for the new visual direction.",
    ],
  },
  {
    version: "0.4.4",
    label: "TMDb suggestions",
    releasedAt: "2026-03-27",
    entries: [
      "Added server-side TMDb suggestions while typing in the search field.",
      "Rendered suggestions as a separate list below the field without replacing stimulus profiles.",
      "Weighted short, likely title completions higher in TMDb relevance sorting.",
    ],
  },
  {
    version: "0.1.0",
    label: "MVP baseline",
    releasedAt: "2026-03-22",
    entries: [
      "Shipped the first search and detail surface with accessibility goals and mock data.",
      "Added the initial explanation system, usage guidance and semantic UI building blocks.",
    ],
  },
] as const;
